model:
  name: bank
dependencies:
generators:
  namespaces:
    - bank.*
    - com.rosetta.model
  tabulators:
    types:
      - cdm.event.workflow.WorkflowStep
      - cdm.event.common.TradeState
      - drr.regulation.common.ReportableEvent
    annotations:
      - projection
      - enrichment